name: Build Application
on: [pull_request]
jobs:
  build:
    name: Gradle Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, windows-latest ]
      fail-fast: false
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Create MacOS installer
        if: startsWith(matrix.os, 'mac')
        run: |
          ./gradlew --info --stacktrace jpackage
          echo "OUTPUT_FILE=$(find build/jpackage -name "*.dmg" -exec realpath {} \;)" >> $GITHUB_ENV
      - name: Create Linux installer
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          ./gradlew --info --stacktrace jpackage
          export OUTPUT_FILE="build/jpackage/*"
      - name: Create Windows installer
        if: startsWith(matrix.os, 'windows')
        run: |
          $env:Path += ";%cd%\wix314-binaries"; .\gradlew jpackage --info --stacktrace
          echo "OUTPUT_FILE=$(find build/jpackage -name "*.exe" -exec realpath {} \;)" >> $GITHUB_ENV
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: $OUTPUT_FILE

      - name: Upload Mac Artifact
        if: startsWith(matrix.os, 'mac')
        uses: actions/upload-artifact@v4
        with:
          name: fqlite-${{ matrix.os }}
          path: $OUTPUT_FILE
      - name: Upload Windows Artifact
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: fqlite-${{ matrix.os }}
          path: $OUTPUT_FILE