name: Build Application
on: [pull_request]
jobs:
  build:
    name: Gradle Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Create MacOS installer
        if: startsWith(matrix.os, 'macOS')
        run: ./gradlew --info --stacktrace jpackage -Pplatform='mac'
      - name: Create Linux installer
        if: startsWith(matrix.os, 'ubuntu')
        run: ./gradlew --info --stacktrace jpackage -Pplatform='lin'
      - name: Create Windows installer
        if: startsWith(matrix.os, 'windows')
        run: $env:Path += ";%cd%\wix314-binaries"; .\gradlew jpackage -Pplatform="win" --info --stacktrace
      - name: Upload Mac Artifact
        if: startsWith(matrix.os, 'macOS')
        uses: actions/upload-artifact@v4
        with:
          name: fqlite-${{ matrix.os }}
          path: build/jpackage/*.dmg